### ISSUE TITLE
[Feature] Packaging monorepo 

### ISSUE THREAD

**Issue by Sushentsev** [adriangb/python-monorepo#2]
It will be nice to have the example of packaging monorepo with relative paths (as you have). I have searched for it a while however did not find anything enough good.

**Comment by adriangb** [comment]
Sorry but I'm confused as to what the point of this issue is. Are you asking for me to change something on this repo? Or just saying thank you?

**Comment by Sushentsev** [comment]
Yes, thank you very much for your example.
You've suggested to write a building packages with relative paths in Poetry issues, I've added it here as nice to implement from your side because I can't do it on my own.

**Comment by adriangb** [comment]
Are you referring to building a _wheel_ for `app` in this example repo?

**Comment by Sushentsev** [comment]
Yes. I know that it can be done by ".sh" script which parses pyproject.toml file and replace relative paths. It sounds not good for me. If you know how to make it with Poetry functionalities, it will be grate.

**Comment by adriangb** [comment]
Sorry but I can’t do that for you, it’s not a use case I  personally have and it’s not trivial to do. I can’t just do work for free. Please consider sponsoring open source authors before asking them for this sort of thing

**Comment by Sushentsev** [comment]
It is okay, I though that it is a use case for you. Let's close the issue, thank you for response)
